import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * Swagger DTO for the RFC 9457 Problem Details response body.
 *
 * Covers the five standard members defined by the spec.
 * For extension members (e.g. `errors`, `balance`), extend this class
 * and add `@ApiProperty()` decorators to the additional fields.
 */
export class ProblemDetailDto {
  @ApiPropertyOptional({
    description: 'A URI reference that identifies the problem type.',
    example: 'about:blank',
  })
  type?: string;

  @ApiPropertyOptional({
    description: 'A short, human-readable summary of the problem type.',
    example: 'Not Found',
  })
  title?: string;

  @ApiProperty({
    description: 'The HTTP status code generated by the origin server.',
    example: 404,
  })
  status!: number;

  @ApiPropertyOptional({
    description: 'A human-readable explanation specific to this occurrence.',
    example: 'The requested resource was not found.',
  })
  detail?: string;

  @ApiPropertyOptional({
    description: 'A URI reference that identifies the specific occurrence.',
  })
  instance?: string;
}

/**
 * Swagger DTO for a single Tier 2 structured validation error.
 * Matches the shape produced by `ProblemDetailsFactory.flattenValidationError()`.
 */
export class ValidationErrorDto {
  @ApiProperty({
    description: 'The property that failed validation.',
    example: 'email',
  })
  property!: string;

  @ApiPropertyOptional({
    description: 'Constraint name → error message map.',
    example: { isEmail: 'email must be an email' },
    type: 'object',
    additionalProperties: { type: 'string' },
  })
  constraints?: Record<string, string>;

  @ApiPropertyOptional({
    description: 'Nested validation errors for child properties.',
    type: () => [ValidationErrorDto],
  })
  children?: ValidationErrorDto[];
}

/**
 * Swagger DTO for validation error responses (Tier 2 structured errors).
 *
 * Extends ProblemDetailDto with the `errors` array containing
 * structured validation error objects with property names, constraint
 * messages, and optional nested children.
 *
 * For Tier 1 flat string arrays (default NestJS ValidationPipe without
 * `Rfc9457ValidationException`), users should create their own DTO
 * or use `ProblemDetailDto` directly with a manual `@ApiProperty()`.
 */
export class ValidationProblemDetailDto extends ProblemDetailDto {
  @ApiProperty({
    description: 'Structured validation errors.',
    type: [ValidationErrorDto],
  })
  errors!: ValidationErrorDto[];
}
